### ISSUE TITLE
Need way to show torrent in file manager (Finder, etc.)

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-app#109]
`shell.showItemInFolder(fullPath)` will come in handy.

http://electron.atom.io/docs/v0.36.8/api/shell/

**Comment by ngoldman** [comment]
![screen shot 2016-03-08 at 9 09 24 pm](https://cloud.githubusercontent.com/assets/427322/13625963/11b6678c-e572-11e5-8974-a76dfd113002.png)

**Comment by ChrisMorrisOrg** [comment]
Instead of a right-click menu, maybe we could use an icon next to the "Files" heading when the user expands a torrent?

![screen shot 2016-03-12 at 7 51 40 pm](https://cloud.githubusercontent.com/assets/2949020/13722023/ddce2afa-e88b-11e5-828c-97ff6038bc6b.png)

**Comment by feross** [comment]
I like your suggestion @ChrisMorrisOrg

**Comment by feross** [comment]
This is done now. @dcposch completed this.
