### ISSUE TITLE
Add Unity Launcher Shortcuts (Linux)

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-app#116]
In Unity, you can add custom entries to its launcher. Similar to the OS X Dock issue #113, let's add Unity Launcher Shortcuts for Linux:

![shortcuts](https://cloud.githubusercontent.com/assets/121766/13633255/b8d22490-e5a2-11e5-809c-1167d8a79a59.png)

API Docs: http://electron.atom.io/docs/v0.36.8/tutorial/desktop-environment-integration/#unity-launcher-shortcuts-linux

**Comment by grunjol** [comment]
@feross just update PR #194 to catch up with master and config.ROOT_PATH change
