### ISSUE TITLE
Releasing builds for linux/mac/windows

### ISSUE THREAD

**Issue by rom1504** [feross/webtorrent-app#12]
Is it easy to build for several platform and put it in a github release ?

Anyway I think it can be important ,once the app is ready, for people that don't want to install node.js (themselves). Especially on windows(/mac).

**Comment by ngoldman** [comment]
Yep, there's https://github.com/electron-userland/electron-packager or https://www.npmjs.com/package/electron-builder for building, and https://www.npmjs.com/package/publish-release or https://github.com/ngoldman/gh-release for releasing to github. Probably lots of others out there too.

**Comment by feross** [comment]
Yeah, so far we haven't introduced any native dependencies. As long as we're careful never to do that, we won't need to manually compile on each platform in order to produce an executable for each platform.

You can run `npm run build` right now to produce final release builds for all platforms. It's currently using `electron-packager` :)

**Comment by feross** [comment]
OS X apps are usually bundled into a `.dmg` file so the user can see a friendly "Drag this app onto the Applications folder" Finder window. Is there an easy way to get `electron-packager` to build us one of those?

How do we bundle the Windows version? Looks like there's lots of files in the output folder, like .DLLs, that are required by, but not embedded within, `WebTorrent.exe`. No idea how to ship this to users.

Same with the Linux release. Can we make a `.deb` file for Ubuntu/Debian?

cc @maxogden @mafintosh - do you guys have any thoughts?

**Comment by maxogden** [comment]
Check out https://www.npmjs.com/package/electron-builder, though I haven't
used it

**Comment by feross** [comment]
The first WebTorrent release (v0.0.0) is live! You can get it from the GitHub releases page here: 

https://github.com/feross/webtorrent-app/releases/tag/v0.0.0

There's a .dmg file for easy installation on OS X. There is a built-in auto-updater so users will get improvements automatically. New releases (if any exist) are downloaded over `https` on app startup, checked to make sure they're signed correctly, and installed the next time the app is restarted.

I'm going to release v0.0.1 later tonight to test that the auto-updater is working as expected!

**Comment by feross** [comment]
We have releases for all platforms. Windows has an installer now. The linux one is just a folder of files for now. Closing this!
