### ISSUE TITLE
Create WebTorrent app icon

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-app#120]
We need an app icon that shows up in the OS X Dock, Windows Start Menu, etc.

There's already a WebTorrent sticker, so I'm going to start playing around with that as a starting point.

![webtorrent-hearts-no-v2](https://cloud.githubusercontent.com/assets/121766/13660483/48b5c2f0-e63f-11e5-9e87-17b3ea0e638c.png)

**Comment by feross** [comment]
v1

![webtorrent-v1](https://cloud.githubusercontent.com/assets/121766/13660493/6a11ea82-e63f-11e5-8aa7-0bce4d10c7a9.png)

**Comment by feross** [comment]
v2

![webtorrent-v2](https://cloud.githubusercontent.com/assets/121766/13660504/89492816-e63f-11e5-8508-5815b00d156a.png)

**Comment by feross** [comment]
v2

![webtorrent-v2](https://cloud.githubusercontent.com/assets/121766/13660522/b631560a-e63f-11e5-8c8a-47246c9bc00a.png)

**Comment by feross** [comment]
v3

![webtorrent-v3](https://cloud.githubusercontent.com/assets/121766/13660526/bc1987ea-e63f-11e5-8734-04a7c43cabcc.png)

**Comment by feross** [comment]
Feedback? Suggestions?

**Comment by yoshuawuyts** [comment]
iterating from v1 onwards would be nice, v3 feels a bit passé; v2 doesn't really embrace the "p2p" aspect I feel (tho perhaps it doesn't have to)

**Comment by yoshuawuyts** [comment]
I quite liked the grid of hearts from the sticker tho, haha - very cute

**Comment by feross** [comment]
It needs to look good at small sizes for when it's in the various app launchers, so less detail is probably better. Take a look:

<img src="https://cloud.githubusercontent.com/assets/121766/13660493/6a11ea82-e63f-11e5-8aa7-0bce4d10c7a9.png" width="50">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://cloud.githubusercontent.com/assets/121766/13660522/b631560a-e63f-11e5-8c8a-47246c9bc00a.png" width="50">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://cloud.githubusercontent.com/assets/121766/13660526/bc1987ea-e63f-11e5-8734-04a7c43cabcc.png" width="50">

**Comment by ChrisMorrisOrg** [comment]
I prefer v3 out of all of them.

**Comment by zeke** [comment]
@feross do you have an SVG of the WebTorrent sticker?

**Comment by DiegoRBaquero** [comment]
I have no idea what I did but...  
![logo](https://cloud.githubusercontent.com/assets/2006839/13661174/081e5754-e66f-11e5-883f-4aa11acf87d4.png)

**Comment by jakefb** [comment]
@feross v3 is good, I wonder what a light background color would look like though

**Comment by dcposch** [comment]
v3 is sweet. agree that the bg could be lighter

**Comment by feross** [comment]
@zeke Yes, you can get the SVG here: https://github.com/feross/stickers/blob/master/webtorrent.svg

**Comment by feross** [comment]
v3.1

![webtorrent-v3 1](https://cloud.githubusercontent.com/assets/121766/13661317/867255ac-e646-11e5-9b2b-4ea4d8e44661.png)

And a smaller version:

<img src="https://cloud.githubusercontent.com/assets/121766/13661317/867255ac-e646-11e5-9b2b-4ea4d8e44661.png" width="50">

**Comment by ChrisMorrisOrg** [comment]
3.1 > 3

**Comment by feross** [comment]
I think this looks pretty excellent, if you ask me:

<img width="707" alt="screen shot 2016-03-09 at 11 42 27 pm" src="https://cloud.githubusercontent.com/assets/121766/13662608/a23bced0-e650-11e5-9a51-0ed0877d8384.png">

**Comment by swift11** [comment]
v1 without the hart

**Comment by feross** [comment]
@zeke It's a hex editor :) http://www.suavetech.com/0xed/

**Comment by callodacity** [comment]
@feross hey just wondering what app you used to make the icon? (if any)

**Comment by feross** [comment]
Affinity Designer
