### ISSUE TITLE
Package for Debian

### ISSUE THREAD

**Issue by nodiscc** [feross/webtorrent-app#122]
Hi, a Debian package for webtorrent-app would be nice. I've tried creating one with [fpm](https://github.com/jordansissel/fpm); running `fpm -s npm -t deb` inside the directory does not create a working Debian package (no binary to run from /usr/local/bin).

**Comment by ngoldman** [comment]
Packaging into app form is done with the `npm run package` script. There hasn't been a formal release yet so it might be a little early to release a debian package too :)

**Comment by feross** [comment]
@nodiscc We're going to publish binaries soon, including one that should work on Debian. In the meantime, you can build the app with `npm run package`.
