### ISSUE TITLE
Closing video player without pausing causes power saving mode to remain disabled

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-app#141]
cc @ungoldman

**Comment by ungoldman** [comment]
Hmm so we should make sure to stop powerSaverBlocker when the window closes, right?

**Comment by feross** [comment]
No, closing the window is already causing a pause.

I meant closing the video player and returning to the torrent list view.

**Comment by ungoldman** [comment]
Oh really? I thought I was seeing the `video-paused` event fire in a console.log when I was testing earlier. Will take a look.

**Comment by ungoldman** [comment]
Okay I can repro, sorry I missed that one. I guess another `ipcRenderer.send` from `closePlayer()` in `index.js` would do the trick though it doesn't feel super clean.

**Comment by ungoldman** [comment]
I think it would make sense to store video playback position when leaving the player in the future so it makes sense to group some actions around that event. For now that's attached to the `back` event so I'll just add something in that context.

**Comment by feross** [comment]
I think we should try to keep the main process unaware of the player state.
If the renderer wants to disable power saving mode, it should just send an
event that does that. That's how most of the events except for the play and
pause ones already work.

**Comment by ungoldman** [comment]
#142 should fix this issue, also moves powerSaveBlocker logic into renderer.
