### ISSUE TITLE
Tooltips on all buttons

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-app#189]
- [x] We should use the `title=""` attribute to provide tooltips on all buttons in the app.
- [x] The ones that already have tooltips need to be capitalized correctly, i.e. "Back" instead of "back".

This will help new users and accessibility tool users.

**Comment by ChrisMorrisOrg** [comment]
I was going to raise this issue too. We should also be able to tab between controls.

**Comment by feross** [comment]
@ChrisMorrisOrg Want to send a PR?

**Comment by ungoldman** [comment]
re: tabbing between controls, should be fairly easy with [`tabindex=0`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex)

**Comment by dcposch** [comment]
#195, coming soon

**Comment by dcposch** [comment]
done
