### ISSUE TITLE
[ui bug] header not visible when player active

### ISSUE THREAD

**Issue by ungoldman** [feross/webtorrent-app#211]
Looks like some recent CSS changes have made the header invisible when the player is active. Also means user is stuck in player mode and has to quit to get back to index.

![screen shot 2016-03-23 at 11 09 51 pm](https://cloud.githubusercontent.com/assets/427322/14009795/b6daa4d6-f14c-11e5-8123-8d296d996e39.png)

PR incoming.

**Comment by feross** [comment]
FYI, hitting ESC also works :)
