### ISSUE TITLE
AirPlay scrubber does not sync between desktop and Apple TV

### ISSUE THREAD

**Issue by ChrisMorrisOrg** [feross/webtorrent-app#22]
I have not tested this on a Chromecast, but I suspect this issue _may_ also apply there.

Currently, if you're streaming a torrent within the WebTorrent desktop app and then click on the AirPlay icon, the video will restart playing on desktop while simultaneously streaming to your Apple TV. This is different behaviour to what is typically seen when a user is browsing the Web and decides to AirPlay an HTML5 video.

**Expected behaviour:**

- The user clicks the AirPlay icon
- A placeholder image appears stating that the video is being streamed, essentially turning the desktop app into a remote control for the Apple TV

<img width="244" alt="airplay placeholder" src="https://cloud.githubusercontent.com/assets/2949020/13550763/de96d4b8-e378-11e5-8bf2-8f51ed685d62.png">
- The placeholder image prevents having two screens and two sets of speakers playing the same video
- Playback of the video on Apple TV will start at timecode when the user clicked the AirPlay icon
- The scrubber controls on both Apple TV and desktop apps should mirror each other - i.e. the scrubbers should match all the time, and if the user pauses/resumes on either the desktop app or the Apple TV, both scrubbers should pause/resume.

**Actual behaviour:**
- The user clicks the AirPlay icon
- The video on the desktop app rewinds to the start and begins playing again
- Streaming is not mirrored between the desktop app and Apple TV - i.e. pausing one won't pause the other

This issue leads me to a question - when a user clicks AirPlay, does WebTorrent.app actually re-start the torrent download, or does it stream what the user has already downloaded so far in the desktop app?

**Comment by ngoldman** [comment]
Same thing on chromecast, streaming to devices is still very experimental. Thanks for the thorough bug report :)

**Comment by ChrisMorrisOrg** [comment]
No worries :). I'm happy to have a go at fixing, or at least improving this. At the very least, the video should not restart on desktop when the user starts streaming via AirPlay/Chromecast.

I am really curious about whether starting a stream on AirPlay will restart the torrent download or use what is cached.

**Comment by feross** [comment]
The behavior where you click the chromecast/airplay button and the video restarts was a bug related to creating a new http server. I just fixed that, but all your other points are correct :)

In particular, thanks for explaining why the video is usually replaced with a placeholder. I always assumed it was for battery life reasons or something.

**Comment by feross** [comment]
> I am really curious about whether starting a stream on AirPlay will restart the torrent download or use what is cached.

The torrent download is not restarted, don't worry.

**Comment by ChrisMorrisOrg** [comment]
Fantastic! :)

Really loving the progress on this app. It's looking great!

**Comment by feross** [comment]
> I'm happy to have a go at fixing, or at least improving this.

You should!

If you have a chromecast, you'll probably have an easier time fixing it there first because the chromecasts package is really well documented and generally excellent: https://github.com/mafintosh/chromecasts thanks to @mafintosh.

**Comment by feross** [comment]
The airplay package has no docs and is generally a bit jankier, so you might have to look at their source code to see how to seek the airplay device.

**Comment by ngoldman** [comment]
Just noting here that when streaming a video to chromecast, if you go back to the torrent list the chromecast streaming will stop shortly thereafter. Was expecting it would keep streaming until I started streaming something else.

**Comment by ChrisMorrisOrg** [comment]
I'll dig into it. I haven't got a Chromecast at the moment, I might grab one today.

**Comment by ChrisMorrisOrg** [comment]
> Just noting here that when streaming a video to chromecast, if you go back to the torrent list the chromecast streaming will stop shortly thereafter. Was expecting it would keep streaming until I started streaming something else.

This could be fixed if videos are opened in a new window? #5

**Comment by ngoldman** [comment]
@ChrisMorrisOrg chromecasts are pretty cheap and handy, though not without bugs. @mafintosh has another great project with similar functionality to what we're working on here: https://mafintosh.github.io/playback/

**Comment by ChrisMorrisOrg** [comment]
Thanks, I'll check both of those projects out :).

**Comment by feross** [comment]
cc @watson – Yo Thomas, we could really use a better Airplay package for the WebTorrent app. The current one is super janky, as I mentioned to you on IRC before.

Once we get a beta version of the app released (next few days hopefully), I want to look at swapping out  the Airplay package for something better.

I think we should write one from scratch, using the existing module and @mafintosh's `chromecasts` as a model. Shouldn't be too hard, I think.

**Comment by dcposch** [comment]
Fixed. The scrubber now tracks progress in both Chromecast and Airplay

https://github.com/feross/webtorrent-app/pull/171

Airplay is still flaky though, and we could def use a better airplay package!
