### ISSUE TITLE
Windows: Show app version in the menu

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-app#220]
There's no OS X app menu that shows the version for free:

<img width="219" alt="screen shot 2016-03-25 at 5 02 55 am" src="https://cloud.githubusercontent.com/assets/121766/14043901/dc3a16da-f246-11e5-85d2-86a48c1352d8.png">

<img width="396" alt="screen shot 2016-03-25 at 5 03 09 am" src="https://cloud.githubusercontent.com/assets/121766/14043903/e12455f2-f246-11e5-9b13-ca43f6a6a0cc.png">

So the very least we can do is to show the version as a disabled (text-only) menu item in the Help menu.

"WebTorrent v0.1.0"

**Comment by feross** [comment]
Does Linux need this too?

**Comment by grunjol** [comment]
Linux needs about window too.

https://github.com/atom/electron/blob/master/docs/api/menu-item.md

Role 'about' is OSX only feature.

**Comment by feross** [comment]
Fixed in https://github.com/feross/webtorrent-app/pull/235
