### ISSUE TITLE
Audio not getting played in some torrents

### ISSUE THREAD

**Issue by tusharmath** [feross/webtorrent-app#221]
Example: `magnet:?xt=urn:btih:E1F9B8B52ACDCA99D66F07CEA7C199E0875310CB&dn=house+of+cards+2013+s04e08+720p+webrip+x264+deflate+ettv&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fglotorrents.pw%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce`

**Comment by grunjol** [comment]
Codec: AC-3 (ATSC A/52)
Channels: Surround 5.1
Sample Rate: 48000 Hz
Bitrate: 640 kbps

AC-3 is not supported

**Comment by Spurlos** [comment]
Could the AC-3 support be added sometime in future?

**Comment by feross** [comment]
Please do not open issues that contain links to copyrighted content. Do not use WebTorrent for copyright infringement, or ask for support with pirate links included. We cannot help with requests like that.
