### ISSUE TITLE
Ubuntu first-run crash

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-app#224]
<img width="490" alt="screen shot 2016-03-25 at 6 36 48 pm" src="https://cloud.githubusercontent.com/assets/121766/14057311/180a1b84-f2b9-11e5-8066-4e1fe409d334.png">

**Comment by grunjol** [comment]
@feross you are right, if you run it with a clear OS installation the icons directory is not present.
PR sent

**Comment by feross** [comment]
Thanks for the PR, but I already fixed this in a local branch :)
