### ISSUE TITLE
config.json paths to .torrent and poster images wrong in some cases

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-app#228]
If the user opens the app from the .DMG disk image, then the config.json will get populated with paths like:

/Volumes/WebTorrent/WebTorrent.app/Contents/Resources/app.asar/static/bigBuckBunny.jpg

Then if they move the app to the Applications folder, unmount the volume, and launch WebTorrent from the Applications folder, the poster images will be broken.

**Comment by ungoldman** [comment]
Would it be weird to have a config item tied to the WebTorrent app's location that gets reevaluated on startup for cases like the above?

**Comment by feross** [comment]
We could just use a relative path, or install the default torrents and their images into the correct "Application Support" folder so we can continue using an absolute path.

**Comment by feross** [comment]
Fixed by @dcposch in #229.
