### ISSUE TITLE
persistent state

### ISSUE THREAD

**Issue by ngoldman** [feross/webtorrent-app#24]
Currently the app loses the torrent list every time the main window closes or is reloaded, and when the app is restarted. Ideally state is stored on disk somewhere so that sessions are just resuming what's already been in progress beforehand.

Looking for good modules (or just vanilla solutions, like a state.json?) to solve this issue. Currently avoiding anything that requires native dependencies or grows the dependency graph in a big way.

- https://github.com/LinusU/node-application-config
    - This module is used by ghauth and has worked well for me in the past. Might be too small for handling things like the torrent list and video playback state once more things need to be tracked, but works for basics and would still be useful for storing application preferences in the future (like default download directory).

**Comment by feross** [comment]
> Currently avoiding anything that requires native dependencies or grows the dependency graph in a big way.

+1

I don't think we need to track that much. A plain object that's `JSON.stringify()`able will work fine for most of our state. https://github.com/LinusU/node-application-config looks great to me.

**Comment by feross** [comment]
I've generally been trying to put state that's ephemeral and can be thrown away on app exit into `state.view`. Stuff that's outside that `state.*` should be persisted to disk.

Right now, stuffs a bit disorganized there, but I think it's worth preserving a distinction here.

**Comment by ngoldman** [comment]
Maybe something like a `state.session` object would make sense to namespace all things that are session specific?

**Comment by ngoldman** [comment]
(thinking eventually other things will be session specific outside of managing view state)

**Comment by ngoldman** [comment]
Could use `node-application-config` to read/write from config to `state.config` too

**Comment by feross** [comment]
@ngoldman That sounds fine to me

**Comment by feross** [comment]
Why not use `node-application-config` to read/write the whole state object, minus `state.session`?

**Comment by ngoldman** [comment]
Whichever's easier 😜

**Comment by dcposch** [comment]
node-application-config looks jank. 2 stars on github, 43 downloads this week.

it also doesn't do file locking as far as i can tell, so there's nothing to prevent two instances of the app running and clobbering each other's state files

**Comment by feross** [comment]
@dcposch GitHub stars and downloads per week don't mean anything if the package works :)

I think it looks like a good start anyway, specifically how it stores state in the right OS-specific location: https://github.com/LinusU/node-application-config-path/blob/master/index.js

Maybe we can PR locking to it?

**Comment by ngoldman** [comment]
Totally agree, it's not about the stars and downloads. That said, https://www.npmjs.com/package/application-config is the right package (not https://www.npmjs.com/package/node-application-config), which got about 11,353 downloads last month :)
