### ISSUE TITLE
Video is looping automatically

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-app#32]
The video should just stop when it's finished, not restart again. Not sure how this is happening since there's no `loop` attribute added to the video tag like `<video loop>`.

Very strange.

**Comment by feross** [comment]
Ah, this is probably happening in the player view code because `videoElement.paused` becomes `true` when the video ends, so it calls `videoElement.play()` :)

**Comment by ngoldman** [comment]
hehe

**Comment by Flet** [comment]
Cool this looks like it was just fixed a few hours ago bt @liamgray: https://github.com/feross/webtorrent-app/commit/9324765db98867cd87c766b518148d8d8283508d
