### ISSUE TITLE
Need better placeholder when torrent screenshot is not ready yet

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-app#42]
When there's not enough data to show a torrent screenshot, the background is black:

![screen shot 2016-03-05 at 8 11 25 pm](https://cloud.githubusercontent.com/assets/121766/13552220/a4081e0c-e30e-11e5-8561-7fc74860e032.png)

We can do better.

**Comment by giuscri** [comment]
Hash the blob obtained so far, map the hash to a value from a list of light/soft/_solarized_ colors and use that as the background. :3

**Comment by ngoldman** [comment]
@giuscri sounds fun but I think that would prove rather expensive. I tried something simple in #57.

**Comment by feross** [comment]
Fixed in #57
