### ISSUE TITLE
Simplify speed/size numbers in the UI

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-app#50]
We want to be the simplest torrent client! :smile: 

No one cares if they're getting 850.62 KB/s or 850.91 KB/s as their download speed.

Let's round with `Math.floor()` in `pretty-bytes`, like we already do for the progress percentage.

![screen shot 2016-03-06 at 1 16 34 am](https://cloud.githubusercontent.com/assets/121766/13553299/9c221186-e339-11e5-9ff3-576c97af91b8.png)

**Comment by ngoldman** [comment]
@feross that doesn't quite work for now:

```
<span>↓ ${prettyBytes(Math.floor(torrent.downloadSpeed || 0))}/s</span>
<span>↑ ${prettyBytes(Math.floor(torrent.uploadSpeed || 0))}/s</span>
```

`pretty-bytes` does the conversion to `nB` and places the decimal afterwards. We could go in and manipulate the string, or fork `pretty-bytes`. I agree decimals aren't necessary for upload/download speed, but I think it's still important for file size. Big difference between 1.01 GB and 1.91 GB.

**Comment by rom1504** [comment]
What about 1.01 MB/s and 1.92 MB/s

**Comment by rom1504** [comment]
The limit should probably be on the number of [Significant figures](https://en.wikipedia.org/wiki/Significant_figures).

**Comment by feross** [comment]
@rom1504 Yeah, you make a good point. Reducing the max decimals to one digit could improve your example so:

1.01 MB/s -> 1.0 MB/s
1.92 MB/s -> 1.9 MB/s

And you're right that sig figs is closer to what we want.

**Comment by Flet** [comment]
Closed with #93?

**Comment by feross** [comment]
@Flet Yes.

**Comment by feross** [comment]
Just sent a PR to clean up that module a lot: https://github.com/Flet/prettier-bytes/pull/1
