### ISSUE TITLE
Hide menu bar in full screen

### ISSUE THREAD

**Issue by rom1504** [feross/webtorrent-app#51]
![full-screen-webtorrent-app](https://cloud.githubusercontent.com/assets/2346494/13554717/ea546964-e3af-11e5-9d97-ea0b466b06a7.png)

On ubuntu with kde. I don't know if it happens with other desktop environments

**Comment by giuscri** [comment]
Same on LXDE

**Comment by dcposch** [comment]
Looks fine on Ubuntu with Unity

![image](https://cloud.githubusercontent.com/assets/169280/13559459/3ef5b2fc-e3c9-11e5-87e6-9c6027264b48.png)

Ubuntu is the standard desktop Linux, the most common by far.

The rabbit hole of alternative setups -- LXDE, KDE, older versions of Gnome, xmonad, etc etc--goes pretty deep. I don't know if we want to support all that.

(If it can be done without hacks, I'm cool with it. However, we're calling the built-in Electron `BrowserWindow.setFullScreen()` call. This Just Works on the three standard desktops: Windows, OSX, and Ubuntu.)

**Comment by ngoldman** [comment]
It would be nice to support edge cases but @dcposch makes a very good point about the variety of linux distros. @rom1504 @giuscri I think PRs are welcome if you can come up with a solution but priority will probably be given to making sure it works as intended on the big three.

**Comment by rom1504** [comment]
playback works just fine on kubuntu. I'll try to figure out what is going wrong here. Maybe this can help https://github.com/mafintosh/playback/blob/67b9d034094b3fd4954fafdd5e156e8e44c39163/index.js#L131

**Comment by giuscri** [comment]
@ngoldman, to my understanding this might be a problem that has to be delegated to Electron's source code. I'll try to see if I have to skill to solve it and try a PR...

**Comment by dcposch** [comment]
:+1:
