### ISSUE TITLE
video keeps playing on window close

### ISSUE THREAD

**Issue by ngoldman** [feross/webtorrent-app#52]
### steps to repro

On OS X:

![screen shot 2016-03-06 at 11 31 59 am](https://cloud.githubusercontent.com/assets/427322/13556459/129e5996-e38f-11e5-9628-db044219c2cc.png)

Play a video. Hit the little red button. Sound keeps going.

Since I think we're just showing/hiding the window on close the video never gets paused.

**Comment by giuscri** [comment]
Can't reproduce that on Linux running `lxde`

**Comment by feross** [comment]
@giuscri This is an OS X only issue related to calling `win.hide()` on the browser window.
