### ISSUE TITLE
downloads folder

### ISSUE THREAD

**Issue by ngoldman** [feross/webtorrent-app#53]
Right now downloads just go to `/tmp/webtorrent` and get deleted on restart. This app needs a persistent downloads folder!

## 1. default
What is standard the downloads folder for each OS? For OS X it's `~/Downloads`. Might be good to set default to whatever the OS default is.

## 2. custom
We need a way to set a custom downloads folder location. Perhaps this is the beginning of a preferences view.

**Comment by giuscri** [comment]
A third possibility would be to store streamed content in a `.webtorrent` directory.

**Comment by ngoldman** [comment]
Though the video streaming is prominent I still think of this primarily as a BitTorrent client. Making a distinction between content to be streamed and any other torrent seems odd.

Either way I vote for giving the user the option to control where files are saved, and I think opting for OS defaults is a good way to respect the local environment the app happens to be in.

**Comment by yoshuawuyts** [comment]
having control would be nice

**Comment by ngoldman** [comment]
I poked around and it seems like `~/Downloads` might actually be standard across Windows/Linux/Mac OS X. Can anyone else confirm?

**Comment by yoshuawuyts** [comment]
[Chrome help page](https://support.google.com/chrome/answer/95574?hl=en) says so:
```
Windows Vista/ Windows 7/ Windows 8: \Users\<username>\Downloads
Mac: /Users/<username>/Downloads
Linux: home/<username>/Downloads
```

**Comment by ngoldman** [comment]
:+1: thanks @yoshuawuyts!

**Comment by wsxy162** [comment]
For linux OS，do you know about xdg-user-dirs?  "home/<username>/Downloads" is only
 a hardcoded directory location, "XDG_DOWNLOAD_DIR" would be better. And I still want a custom directory feature.

**Comment by feross** [comment]
@wsxy162 This will be fixed soon.
