### ISSUE TITLE
Traffic lights show over video playback

### ISSUE THREAD

**Issue by ChrisMorrisOrg** [feross/webtorrent-app#86]
Mac OS X's "traffic lights" display over the video even when the user hasn't activated the player controls.

![traffic lights](https://cloud.githubusercontent.com/assets/2949020/13597334/1645bcc2-e56c-11e5-9b7a-839391b93252.png)

**Comment by feross** [comment]
I actually don't think this is so bad. I know that Quicktime automatically hides the header (including traffic lights) when the video is playing, but it's harder to do this with Electron.

You can either get a window with native OS buttons, or a completely "frameless" window. You can read about [Electron frameless windows](https://github.com/atom/electron/blob/master/docs/api/frameless-window.md).

You can't change the type of window once it's created. I opened an issue to see if the developers could allow setting the `frame` option dynamically but it was closed: https://github.com/atom/electron/issues/4652

So, the only way to fix this right now would be to use a frameless window and create our own traffic light buttons in CSS and try to make them match the buttons as closely as possible. This is what [Playback](https://github.com/mafintosh/playback) does, but it's a bit janky. When Apple released a new OS, we have to manually change the buttons or they will look wrong. And when we do, all the users on old OSs will suddenly see the buttons from the latest OS.

No easy solution here.

**Comment by ChrisMorrisOrg** [comment]
Bummer, that's hugely annoying. The solution seems like a lot of work for such a minor change, but at the same time, I really hate overlays when watching videos - it feels similar to when those annoying adverts pop up when you're watching a TV show.

I'm wondering if I should look at Electron itself and see if I can add something to allow for this option.

**Comment by ChrisMorrisOrg** [comment]
QuickTime seems to hide the entire titlebar, not purely the traffic light controls. This might mean that we'd have to use the built-in OS X titlebar. Hmm, maybe it's not worth it.

**Comment by feross** [comment]
> @ChrisMorrisOrg QuickTime seems to hide the entire titlebar, not purely the traffic light controls. This might mean that we'd have to use the built-in OS X titlebar

Even then, I don't think Electron has an API for changing the frame option after a window has been constructed :(

**Comment by ChrisMorrisOrg** [comment]
> @feross Even then, I don't think Electron has an API for changing the frame option after a window has been constructed :(

Yeah, it seems like too much of a hassle. I've asked a few friends what they thought about the app, and they didn't seem overly concerned about the traffic lights. Maybe it's not worth worrying about at this point in time.

**Comment by feross** [comment]
Okay, sounds good to me.
