### ISSUE TITLE
Should resources/ go into webtorrent-fixtures ?

### ISSUE THREAD

**Issue by rom1504** [feross/webtorrent-app#88]
https://github.com/feross/webtorrent-app/tree/master/resources
https://github.com/feross/webtorrent-fixtures/tree/master/fixtures

**Comment by feross** [comment]
@rom1504 I know they look like they contain similar files, but they're actually serving different purposes. The fixtures are for the test suites in the various webtorrent repos, but the `resources/` folder is for torrents that we're actually going to ship by default in the application.

We want users to understand how the app works as soon as they open it, so they'll see some torrents the first time. They can delete them if they want and they won't come back.

![screen shot 2016-03-08 at 5 41 33 pm](https://cloud.githubusercontent.com/assets/121766/13622665/1945ab2e-e555-11e5-8fa4-36384accffa8.png)
