### ISSUE TITLE
Startup speed

### ISSUE THREAD

**Issue by dcposch** [feross/webtorrent-app#89]
- [x] Measure init time (#234)
  - [x] Measure `require()` time, find out which dependencies are loading slowly
  - [x] Get init time under 200ms (from icon click to rendered page)
- [x] Speed up torrent initialization
  - [x] Use torrent files, not magnet links, for the default Blender Foundation videos
  - [x] Once an infohash has been loaded from the DHT, cache or save it
- [x] Reduce waste (#238)
  - [x] Stop `virtualdom` from swapping out every event handler on every tick

**Comment by dcposch** [comment]
**Init time, before**
![image](https://cloud.githubusercontent.com/assets/169280/14063807/97d08758-f396-11e5-80b8-5fc5cafed41f.png)

**Comment by dcposch** [comment]
**Init time, after: 122ms**

![image](https://cloud.githubusercontent.com/assets/169280/14064023/bdf3c338-f3a4-11e5-8755-b3e37b20f216.png)

**Comment by feross** [comment]
This is done now
